---
# tasks file for web-server


    - name              : Install httpd package
      yum               :
        name            : httpd
        state           : installed
      tags              :
        - deploy
                
    - name              : Open port {{ vhost_port }} on Firewall
      firewalld         :
        port            : "{{ vhost_port }}/tcp"
        permanent       : yes
        immediate       : yes
        state           : enabled
      tags              :
         - deploy
                
    - name              : Configure Selinux to allow Apache to listen on tcp port {{ vhost_port }}
      seport            :
        ports           : "{{ vhost_port }}"
        proto           : tcp
        setype          : http_port_t
        state           : present
      tags              :
        - deploy
                        
    - name              : Configure vhosts
      template          :
        src             : vhost-template.j2
        dest            : /etc/httpd/conf.d/{{ ansible_hostname }}-vhost.conf
      notify            : restart_httpd
      tags              :
        - deploy
                
    - name              : Make apache vhost listen to {{ vhost_port }}
      lineinfile        : 
        path            : /etc/httpd/conf.d/{{ ansible_hostname }}-vhost.conf
        regexp          : "^Listen 80"
        line            : "Listen {{ vhost_port }}"
        insertbefore    : BOF
        backrefs        : no
        state           : present
      notify            : restart_httpd
      tags              :
        - deploy
                
    - name              : Start/Enable service 
      service           :
        name            : httpd
        enabled         : yes
      tags              :
        - deploy
                
    - name              : Create Document Root
      file              :
        path            : /vhosts/{{ ansible_hostname }}.example.com/
        state           : directory
      tags              : deploy
                
    - name              : Give Document Root SElinux context label
      sefcontext        :
        target          : '/vhosts(/.*)?'
        setype          : httpd_sys_content_t
        state           : present
      tags              : deploy
                
    - name              : Apply new SELinux file context to filesystem
      command           : restorecon -Rv /vhosts/
      tags              : deploy
                
    - name              : Place Home Page
      file              :
        path            : /vhosts/{{ ansible_hostname }}.example.com/index.html
        state           : touch
      tags              : deploy
                
    - name              : Add home page contents
      lineinfile        :
        path            : /vhosts/{{ ansible_hostname }}.example.com/index.html
        state           : present
        line            : Hello, this is my ansible webpage for host {{ ansible_hostname }}
      tags              : deploy
                
    - name              : Home Page by template
      template          :
        src             : vhost-index-template.j2
        dest            : /vhosts/{{ ansible_hostname }}.example.com/index.html
      tags              : deploy
                
    - name              : backup configuration files
      fetch             :
        src             : /etc/httpd/conf.d/{{ ansible_hostname }}-vhost.conf
        dest            : /backup/fetched/
        validate_checksum       : yes
      ignore_errors     : yes
      tags              : [deploy,backup,destroy]
                
    - name              : backup home pages
      fetch             :
        src             : /vhosts/{{ ansible_hostname }}.example.com/index.html
        dest            : /backup/fetched/
        validate_checksum       : yes
      ignore_errors     : yes
      tags              : [deploy,backup,destroy]
                
    - name              : Close Firewall Port
      firewalld         :
        port            : "{{ vhost_port }}/tcp"
        permanent       : yes
        immediate       : yes
        state           : disabled
      ignore_errors     : yes
      tags              :
         - destroy
                        
    - name              : Stop/Disable service 
      service           :
        name            : httpd
        state           : stopped
        enabled         : no
      ignore_errors     : yes
      tags              :
        - destroy
                
    - name              : Remove port {{ vhost_port }} from Selinux policy
      seport            :
        ports           : "{{ vhost_port }}"
        proto           : tcp
        setype          : http_port_t
        state           : absent
      ignore_errors     : yes
      tags              :
        - destroy
                
    - name              : Stop apache to listen to {{ vhost_port }}
      lineinfile        : 
        path            : /etc/httpd/conf.d/{{ ansible_hostname }}-vhost.conf
        line            : "Listen {{ vhost_port }}"
        state           : absent
      ignore_errors     : yes
      tags              :
        - destroy
                
    - name              : Remove vhost configuration file
      file              :
        path            : /etc/httpd/conf.d/{{ ansible_hostname }}-vhost.conf
        state           : absent
      ignore_errors     : yes
      tags              : destroy
                
    - name              : Remove httpd package
      yum               :
        name            : httpd
        state           : absent
      ignore_errors     : yes
      tags              :
        - destroy
                
    - name              : Remove Home page contents
      lineinfile        :
        path            : /vhosts/{{ ansible_hostname }}.example.com/index.html
        state           : absent
        regexp          : "Hello"
      ignore_errors     : yes
      tags              : destroy
                
    - name              : Remove Home Page
      file              :
        path            : /vhosts/{{ ansible_hostname }}.example.com/index.html
        state           : absent
      ignore_errors     : yes
      tags              : destroy
                
    - name              : Remove Document Root SElinux context label
      sefcontext        :
        target          : '/vhosts(/.*)?'
        setype          : httpd_sys_content_t
        state           : absent
      tags              : destroy
                        
    - name              : Apply new SELinux file context to filesystem
      command           : restorecon -Rv /vhosts/
      tags              : destroyy
                         
    - name              : Remove Document Root
      file              :
        path            : /vhosts/
        state           : absent
      ignore_errors     : yes
      tags              : destroy

      #    - name              : Checking
      #      shell             :
      #              'rpm -qa | grep httpd-2 2>&1 ; systemctl is-active httpd 2>&1 ; systemctl is-enabled httpd 2>&1 ; firewall-cmd --list-ports 2>&1 ; semanage port -l | grep ^http_port_t 2>&1 ; grep ^Listen /etc/httpd/conf.d/{{ ansible_hostname }}-vhost.conf 2>&1 ; curl -s localhost:{{ vhost_port }} 2>&1 ;  cat /etc/httpd/conf.d/{{ ansible_hostname }}-vhost.conf 2>&1 ; echo ""'
      #      ignore_errors     : yes
      #      tags              : 
      #        - deployy
      #        - destroyy
      #        - checkk
      #        - never
      #      register          : check_out
      
    - name              : Run verification script
      script            :
        cmd             : verification_script.sh {{ ansible_hostname }} {{ vhost_port }}
      ignore_errors     : yes
      register          : check_out
      tags              :
        - deploy
        - destroy
        - check

    - debug             :
       var              : check_out.stdout_lines
      ignore_errors     : yes
      tags              :
        - deploy
        - destroy
        - check
                
...
