---
# handlers file for web-server
#
#  handlers             :
    - name              : restart_httpd
      service           :
        name            : httpd
        state           : restarted
        enabled         : yes

